### ISSUE TITLE
Status for Deserialization ?

### ISSUE THREAD

**Issue by redben** [jsog/jsog-jackson#1]
I have read your discussion with Tatu Saloranta about this (http://markmail.org/message/n6vrh4zi5nm3r3wt)

So I was wondering if you found a way around this deserialization problem ?

**Comment by craigtu** [comment]
Are there any plans to fully implement deserialization for the JSOG Jackson plugin?

**Comment by stickfigure** [comment]
I tried, but couldn't figure it out a solution. It's probably going to take some help from Tatu, which means first making him aware that there are other people besides me who want it. Please ask about JSOG on the jackson-user list. If it keeps coming up, he may prioritize it.

**Comment by redben** [comment]
Just wanted to link the block that seems to be the reason this does not work, for reference
https://github.com/FasterXML/jackson-databind/blob/ef4115cacf4526a69c0613a61b80317a676955df/src/main/java/com/fasterxml/jackson/databind/deser/BeanDeserializerBase.java#L951

Also created a feature request on jackson-databind https://github.com/FasterXML/jackson-databind/issues/622

**Comment by cowtowncoder** [comment]
FWIW, Jackson 2.5.0 (master branch) finally supports deserialization. Not sure if any work is needed here.

**Comment by redben** [comment]
Great, thanks !

**Comment by stickfigure** [comment]
The code here has been updated, all it needs is a release (or release candidate) of 2.5. Thanks Tatu!
