### ISSUE TITLE
Where can I get sample code for deserialising JSOG under Java/Android?

### ISSUE THREAD

**Issue by paipeng** [jsog/jsog-jackson#18]
Hello,

we can successfully use jsog.js to deserialising JSOG to JSON under JS. Now want to get it work also on Android/Java. I am still not sure how it works? Is there any sample code?

Thanks

Pai

**Comment by stickfigure** [comment]
Have you looked at the tests for this project?

https://github.com/jsog/jsog-jackson/blob/master/src/test/java/com/voodoodyne/jackson/jsog/JSOGTest.java

AFAIK Jackson works the same on Android as it does in the standard JRE.
