### ISSUE TITLE
Deserialization issue when adding  @JsonTypeInfo

### ISSUE THREAD

**Issue by ericali78** [jsog/jsog-jackson#2]
First happy new year to everybody !
Deserialization seems to work. However when adding  @JsonTypeInfo (need this in a model object that have superclass), it does not succeed to.

Sample to reproduce in JSOGTest.java :

@JsonIdentityInfo(generator=JSOGGenerator.class)
@JsonTypeInfo(use=JsonTypeInfo.Id.CLASS, include=JsonTypeInfo.As.PROPERTY, property="@class")
    public static class Inner {
        public String bar;
    }
In a more global way, the @class attribute does not seem to be handle or lead to a conflict with @ref management.
Does somebody succed to handle that ? thank you .

**Comment by ericali78** [comment]
Hello, 
Here and additionnal info :+1: 
the serialization is ok.
-> Serialized to: {"@id":"1","foo":"foo","inner1":{"@class":"com.voodoodyne.jackson.jsog.JSOGTest$Inner","@id":"2","bar":"bar"},"inner2":{"@ref":"2"}}

But when attempting to deserialize it fails because jacksson thinks that {"@class":"com.voodoodyne.jackson.jsog.JSOGTest$Inner","@id":"2","bar":"bar"} represents an objectid or reference

stack trace :
Caused by: java.lang.NullPointerException
at com.voodoodyne.jackson.jsog.JSOGRefDeserializer.deserialize(JSOGRefDeserializer.java:38)
at com.voodoodyne.jackson.jsog.JSOGRefDeserializer.deserialize(JSOGRefDeserializer.java:18)
at com.fasterxml.jackson.databind.deser.impl.ObjectIdReader.readObjectReference(ObjectIdReader.java:136)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectId(BeanDeserializerBase.java:1045)
)

**Comment by stickfigure** [comment]
It looks like Jackson is trying to deserialize a Ref even for the non-Ref case. I'll make a test case and submit it as a PR to jackson.

**Comment by ericali78** [comment]
This has been solved in jackson-databind , thank you ;)
