### ISSUE TITLE
Deserialization fails for DeserializationFeature.FAIL_ON_TRAILING_TOKENS feature enabled

### ISSUE THREAD

**Issue by a5phyx** [jsog/jsog-jackson#23]
As stated in the title, library isn't able (i.e. throws exception) to deserialize JSONs containing `@id` / `@ref` properties when `ObjectMapper` has `DeserializationFeature.FAIL_ON_TRAILING_TOKENS` feature enabled.

**Comment by stickfigure** [comment]
Merged and published as 1.1.2. Thanks for the PR!
