### ISSUE TITLE
Deserializing nested objects not working

### ISSUE THREAD

**Issue by koukavoj** [jsog/jsog-jackson#3]
At first, thanks for all the great work on this project.

I'm trying to get the deserialization to work, but no luck.
From client, I'm sending for test this JSOG string:
`{"@id":"1","projectid":"1","contractnumbers":[{"@id":"2","project":{"@ref":"1"}}]}`

But on the server, when deserialized into POJOs I get this structure:
`Project [projectid=1, contractnumbers=[Contractnumber [project=Project [projectid=null]]]]`

The `projectid` in contractnumbers shouldn't be null - it is referenced in the JSOG string correctly.
I expected to get infinite recursion when calling toString() on the server.

I am using jackson version 2.5.0 and jsog-jackson version 1.1.

On the server side I have annotated all the classe with `@JsonIdentityInfo(generator=JSOGGenerator.class)` and `@JsonIgnoreProperties(ignoreUnknown = true)`, No other annotations are present.

Thanks for any advice

**Comment by stickfigure** [comment]
I added a test case here:

https://github.com/jsog/jsog-jackson/blob/master/src/test/java/com/voodoodyne/jackson/jsog/Issue3Test.java

It passes. What is missing?

**Comment by koukavoj** [comment]
You are absolutely right, everything works fine now.

My problem was that in Maven I declared to use jackson 2.5.0 but Wildfly internally uses jackson 2.3.2. After upgrade is everything working fine.

I'm very sorry about bothering you with my mistake.

Thank you

**Comment by stickfigure** [comment]
No problem, glad it is working!

**Comment by jayrmotta** [comment]
Hey @koukavoj how did you figured that? I'm running an embedded Tomcat 8 here and I'm experiencing the same problem but at least in the IntelliJ explorer the jackson-core is 2.5.3.

I've run a `mvn dependency:tree` here and checked that the spring boot starter web is using jackson-core 2.5.3 and jackson-databind 2.4.5, I've tried adding an exclusion and forcing the jackson-databind 2.5.3 in my pom.xml but apparently this spring boot starter web uses some deprecated class that doesn't exist in 2.5.3 anymore so the spring-boot stops working.

Do you guys think that could be the problem?

**Comment by mararn1618** [comment]
Had a similar problem with spring boot. I was using spring boot 1.2.5.RELEASE, which configured jackson to 2.4.3. After upgrading to 1.3.5.RELEASE, jackson went 2.6.6 and the deserialization of JSOG worked.

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <!-- <version>1.2.5.RELEASE</version> -->
    <version>1.3.5.RELEASE</version>
</parent>
```

**Comment by stickfigure** [comment]
Like wine, software gets better with age :-)
