### ISSUE TITLE
Deserialization of simple {"id":№} entities

### ISSUE THREAD

**Issue by Kaned1as** [jsog/jsog-jackson#4]
I'm coming after some discussion  [here](https://github.com/FasterXML/jackson-databind/issues/266)

We have software that sends objects as a set of IDs like in abovementioned link.
We then enrich these IDs with our database objects.
But Jackson can't deserialize multiple entites with same ID because of way forward-referencing is done here.

Hope this issue can somehow help us to find a generic solution that complies with other libraries.

(pls label as enhancement)

**Comment by stickfigure** [comment]
This library is an implementation of the simple, well-defined JSOG specification. Your format is not JSOG.
